### ISSUE TITLE
Docker wireguard and docker wireguard export

### ISSUE THREAD

**Issue by is0x** [MindFlavor/prometheus_wireguard_exporter#88] opened 2022-03-03 08:16 UTC
hello,
I have wireguard in one docker and export in another, but I can't get it to see the wg0 interface, it always tells me not device and when I do a wg show in wireguard export it always returns it empty. How can I do to connect these two docker, because otherwise the metrics come out empty.
![image](https://user-images.githubusercontent.com/48331513/156527669-43040a1e-a275-40a5-9494-394e861a8253.png)

**Comment by rahmadsandy** [comment] 2022-03-06 12:34
would be nice if you certain docker configuration ex: docker-compose.yml

**Comment by qdm12** [comment] 2022-03-09 11:25
Probably run it with `network_mode: host`? Or you can also connect to the Wireguard container and use it as network host with `network_mode: "container:wireguardcontainername"`, although that will lose connection if the wireguard container restarts without the wireguard prom container not restarting as well.

**Comment by qdm12** [comment] 2022-03-09 11:26
Duplicate of #62 too

**Closed by qdm12** 2022-03-09 11:26 UTC
